<a href="https://colab.research.google.com/github/Nithish0807/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard/blob/main/sqlfunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd


conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

print("Connected to in-memory SQLite database.")

Connected to in-memory SQLite database.

In [ ]:
create_table_sql = """
CREATE TABLE Employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    department TEXT NOT NULL,
    salary REAL NOT NULL,
    hire_date TEXT NOT NULL,
    is_active INTEGER
);
"""
cursor.execute(create_table_sql)
conn.commit()
print("Table 'Employees' created successfully.")

Table 'Employees' created successfully.

In [ ]:
employees_data = [
    ('Alice Smith', 'Sales', 60000.00, '2020-01-15', 1),
    ('Bob Johnson', 'Marketing', 55000.00, '2019-03-22', 1),
    ('Charlie Brown', 'IT', 75000.00, '2021-07-01', 1),
    ('Diana Prince', 'HR', 62000.00, '2018-11-11', 1),
    ('Eve Adams', 'Sales', 63000.00, '2020-02-20', 1),
    ('Frank White', 'Marketing', 58000.00, '2019-05-10', 0),
    ('Grace Lee', 'IT', 80000.00, '2022-01-01', 1),
    ('Harry King', 'HR', 65000.00, '2017-09-01', 1),
    ('Ivy Davis', 'Sales', 61000.00, '2020-04-01', 1),
    ('Jack Miller', 'Marketing', 57000.00, '2019-06-15', 1),
    ('Karen Green', 'IT', 78000.00, '2021-09-01', 1),
    ('Liam Hall', 'HR', 68000.00, '2018-03-01', 1),
    ('Mia Young', 'Sales', 64000.00, '2020-05-05', 1),
    ('Noah Clark', 'Marketing', 59000.00, '2019-07-20', 1),
    ('Olivia Lewis', 'IT', 82000.00, '2022-03-01', 0),
    ('Peter Scott', 'HR', 70000.00, '2017-10-10', 1),
    ('Quinn Baker', 'Sales', 66000.00, '2020-06-10', 1),
    ('Rachel Hill', 'Marketing', 60000.00, '2019-08-01', 1),
    ('Sam Taylor', 'IT', 85000.00, '2022-05-01', 1),
    ('Tina Adams', 'HR', 72000.00, '2018-05-01', 1),
    ('Uma Khan', 'Sales', 67000.00, '2020-07-15', 1),
    ('Victor Chen', 'Marketing', 61000.00, '2019-09-01', 1),
    ('Wendy Wu', 'IT', 88000.00, '2022-07-01', 1),
    ('Xavier Lee', 'HR', 74000.00, '2018-07-01', 1),
    ('Yara Singh', 'Sales', 69000.00, '2020-08-20', 1),
    ('Zack Patel', 'Marketing', 62000.00, '2019-10-10', 0),
    ('Amy Wang', 'IT', 90000.00, '2022-09-01', 1),
    ('Ben Davis', 'HR', 76000.00, '2018-09-01', 1),
    ('Cathy Kim', 'Sales', 70000.00, '2020-09-10', 1),
    ('David Chen', 'Marketing', 63000.00, '2019-11-01', 1),
    ('Ella Garcia', 'IT', 92000.00, '2022-11-01', 1)
]

insert_sql = """
INSERT INTO Employees (name, department, salary, hire_date, is_active)
VALUES (?, ?, ?, ?, ?);
"""

cursor.executemany(insert_sql, employees_data)
conn.commit()
print(f"{len(employees_data)} records inserted into 'Employees' successfully.")

31 records inserted into 'Employees' successfully.

In [ ]:
def fetch_and_display(query, description):
    print(f"\n--- {description} ---")
    cursor.execute(query)
    rows = cursor.fetchall()
    columns = [description[0] for description in cursor.description]
    df = pd.DataFrame(rows, columns=columns)
    display(df)


fetch_and_display("SELECT * FROM Employees;", "All Employees")


fetch_and_display("SELECT name, department, salary FROM Employees;", "Name, Department, Salary")


fetch_and_display("SELECT * FROM Employees WHERE department = 'IT';", "Employees in IT Department")


fetch_and_display("SELECT name, salary FROM Employees ORDER BY salary DESC;", "Employees by Salary (Descending)")


fetch_and_display("SELECT name, salary FROM Employees ORDER BY salary DESC LIMIT 5;", "Top 5 Highest Paid Employees")


fetch_and_display("SELECT DISTINCT department FROM Employees;", "Unique Departments")

--- All Employees ---

    id           name department   salary   hire_date  is_active
0    1    Alice Smith      Sales  60000.0  2020-01-15          1
1    2    Bob Johnson  Marketing  55000.0  2019-03-22          1
2    3  Charlie Brown         IT  75000.0  2021-07-01          1
3    4   Diana Prince         HR  62000.0  2018-11-11          1
4    5      Eve Adams      Sales  63000.0  2020-02-20          1
5    6    Frank White  Marketing  58000.0  2019-05-10          0
6    7      Grace Lee         IT  80000.0  2022-01-01          1
7    8     Harry King         HR  65000.0  2017-09-01          1
8    9      Ivy Davis      Sales  61000.0  2020-04-01          1
9   10    Jack Miller  Marketing  57000.0  2019-06-15          1
10  11    Karen Green         IT  78000.0  2021-09-01          1
11  12      Liam Hall         HR  68000.0  2018-03-01          1
12  13      Mia Young      Sales  64000.0  2020-05-05          1
13  14     Noah Clark  Marketing  59000.0  2019-07-20          1
14  15   Olivia Lewis         IT  82000.0  2022-03-01          0
15  16    Peter Scott         HR  70000.0  2017-10-10          1
16  17    Quinn Baker      Sales  66000.0  2020-06-10          1
17  18    Rachel Hill  Marketing  60000.0  2019-08-01          1
18  19     Sam Taylor         IT  85000.0  2022-05-01          1
19  20     Tina Adams         HR  72000.0  2018-05-01          1
20  21       Uma Khan      Sales  67000.0  2020-07-15          1
21  22    Victor Chen  Marketing  61000.0  2019-09-01          1
22  23       Wendy Wu         IT  88000.0  2022-07-01          1
23  24     Xavier Lee         HR  74000.0  2018-07-01          1
24  25     Yara Singh      Sales  69000.0  2020-08-20          1
25  26     Zack Patel  Marketing  62000.0  2019-10-10          0
26  27       Amy Wang         IT  90000.0  2022-09-01          1
27  28      Ben Davis         HR  76000.0  2018-09-01          1
28  29      Cathy Kim      Sales  70000.0  2020-09-10          1
29  30     David Chen  Marketing  63000.0  2019-11-01          1
30  31    Ella Garcia         IT  92000.0  2022-11-01          1

--- Name, Department, Salary ---

             name department   salary
0     Alice Smith      Sales  60000.0
1     Bob Johnson  Marketing  55000.0
2   Charlie Brown         IT  75000.0
3    Diana Prince         HR  62000.0
4       Eve Adams      Sales  63000.0
5     Frank White  Marketing  58000.0
6       Grace Lee         IT  80000.0
7      Harry King         HR  65000.0
8       Ivy Davis      Sales  61000.0
9     Jack Miller  Marketing  57000.0
10    Karen Green         IT  78000.0
11      Liam Hall         HR  68000.0
12      Mia Young      Sales  64000.0
13     Noah Clark  Marketing  59000.0
14   Olivia Lewis         IT  82000.0
15    Peter Scott         HR  70000.0
16    Quinn Baker      Sales  66000.0
17    Rachel Hill  Marketing  60000.0
18     Sam Taylor         IT  85000.0
19     Tina Adams         HR  72000.0
20       Uma Khan      Sales  67000.0
21    Victor Chen  Marketing  61000.0
22       Wendy Wu         IT  88000.0
23     Xavier Lee         HR  74000.0
24     Yara Singh      Sales  69000.0
25     Zack Patel  Marketing  62000.0
26       Amy Wang         IT  90000.0
27      Ben Davis         HR  76000.0
28      Cathy Kim      Sales  70000.0
29     David Chen  Marketing  63000.0
30    Ella Garcia         IT  92000.0

--- Employees in IT Department ---

   id           name department   salary   hire_date  is_active
0   3  Charlie Brown         IT  75000.0  2021-07-01          1
1   7      Grace Lee         IT  80000.0  2022-01-01          1
2  11    Karen Green         IT  78000.0  2021-09-01          1
3  15   Olivia Lewis         IT  82000.0  2022-03-01          0
4  19     Sam Taylor         IT  85000.0  2022-05-01          1
5  23       Wendy Wu         IT  88000.0  2022-07-01          1
6  27       Amy Wang         IT  90000.0  2022-09-01          1
7  31    Ella Garcia         IT  92000.0  2022-11-01          1

--- Employees by Salary (Descending) ---

             name   salary
0     Ella Garcia  92000.0
1        Amy Wang  90000.0
2        Wendy Wu  88000.0
3      Sam Taylor  85000.0
4    Olivia Lewis  82000.0
5       Grace Lee  80000.0
6     Karen Green  78000.0
7       Ben Davis  76000.0
8   Charlie Brown  75000.0
9      Xavier Lee  74000.0
10     Tina Adams  72000.0
11    Peter Scott  70000.0
12      Cathy Kim  70000.0
13     Yara Singh  69000.0
14      Liam Hall  68000.0
15       Uma Khan  67000.0
16    Quinn Baker  66000.0
17     Harry King  65000.0
18      Mia Young  64000.0
19      Eve Adams  63000.0
20     David Chen  63000.0
21   Diana Prince  62000.0
22     Zack Patel  62000.0
23      Ivy Davis  61000.0
24    Victor Chen  61000.0
25    Alice Smith  60000.0
26    Rachel Hill  60000.0
27     Noah Clark  59000.0
28    Frank White  58000.0
29    Jack Miller  57000.0
30    Bob Johnson  55000.0

--- Top 5 Highest Paid Employees ---

           name   salary
0   Ella Garcia  92000.0
1      Amy Wang  90000.0
2      Wendy Wu  88000.0
3    Sam Taylor  85000.0
4  Olivia Lewis  82000.0

--- Unique Departments ---

  department
0      Sales
1  Marketing
2         IT
3         HR

In [ ]:
fetch_and_display("SELECT name, department FROM Employees WHERE name LIKE 'A%';", "Employees with names starting with 'A'")

fetch_and_display("SELECT name, salary FROM Employees WHERE salary BETWEEN 60000 AND 70000 ORDER BY salary;", "Employees with Salary between 60k and 70k")


fetch_and_display("SELECT name, department FROM Employees WHERE department IN ('Sales', 'HR');", "Employees in Sales or HR")


fetch_and_display("SELECT name, department, salary FROM Employees WHERE is_active = 1 AND department = 'IT' AND salary > 80000;", "Active IT Employees with Salary > 80k")


fetch_and_display("SELECT name, department FROM Employees WHERE NOT department = 'Marketing';", "Employees NOT in Marketing")

--- Employees with names starting with 'A' ---

          name department
0  Alice Smith      Sales
1     Amy Wang         IT

--- Employees with Salary between 60k and 70k ---

            name   salary
0    Alice Smith  60000.0
1    Rachel Hill  60000.0
2      Ivy Davis  61000.0
3    Victor Chen  61000.0
4   Diana Prince  62000.0
5     Zack Patel  62000.0
6      Eve Adams  63000.0
7     David Chen  63000.0
8      Mia Young  64000.0
9     Harry King  65000.0
10   Quinn Baker  66000.0
11      Uma Khan  67000.0
12     Liam Hall  68000.0
13    Yara Singh  69000.0
14   Peter Scott  70000.0
15     Cathy Kim  70000.0

--- Employees in Sales or HR ---

            name department
0    Alice Smith      Sales
1   Diana Prince         HR
2      Eve Adams      Sales
3     Harry King         HR
4      Ivy Davis      Sales
5      Liam Hall         HR
6      Mia Young      Sales
7    Peter Scott         HR
8    Quinn Baker      Sales
9     Tina Adams         HR
10      Uma Khan      Sales
11    Xavier Lee         HR
12    Yara Singh      Sales
13     Ben Davis         HR
14     Cathy Kim      Sales

--- Active IT Employees with Salary > 80k ---

          name department   salary
0   Sam Taylor         IT  85000.0
1     Wendy Wu         IT  88000.0
2     Amy Wang         IT  90000.0
3  Ella Garcia         IT  92000.0

--- Employees NOT in Marketing ---

             name department
0     Alice Smith      Sales
1   Charlie Brown         IT
2    Diana Prince         HR
3       Eve Adams      Sales
4       Grace Lee         IT
5      Harry King         HR
6       Ivy Davis      Sales
7     Karen Green         IT
8       Liam Hall         HR
9       Mia Young      Sales
10   Olivia Lewis         IT
11    Peter Scott         HR
12    Quinn Baker      Sales
13     Sam Taylor         IT
14     Tina Adams         HR
15       Uma Khan      Sales
16       Wendy Wu         IT
17     Xavier Lee         HR
18     Yara Singh      Sales
19       Amy Wang         IT
20      Ben Davis         HR
21      Cathy Kim      Sales
22    Ella Garcia         IT

In [ ]:
fetch_and_display("SELECT COUNT(*) AS total_employees FROM Employees;", "Total Number of Employees")

fetch_and_display("SELECT SUM(salary) AS total_salary FROM Employees;", "Total Salary Bill")


fetch_and_display("SELECT department, AVG(salary) AS average_salary FROM Employees GROUP BY department;", "Average Salary by Department")


fetch_and_display("SELECT department, MAX(salary) AS max_salary, MIN(salary) AS min_salary FROM Employees GROUP BY department;", "Max and Min Salary by Department")


fetch_and_display("SELECT department, AVG(salary) AS average_salary FROM Employees GROUP BY department HAVING AVG(salary) > 70000;", "Departments with Average Salary > 70k")

--- Total Number of Employees ---

   total_employees
0               31

--- Total Salary Bill ---

   total_salary
0     2152000.0

--- Average Salary by Department ---

  department  average_salary
0         HR    69571.428571
1         IT    83750.000000
2  Marketing    59375.000000
3      Sales    65000.000000

--- Max and Min Salary by Department ---

  department  max_salary  min_salary
0         HR     76000.0     62000.0
1         IT     92000.0     75000.0
2  Marketing     63000.0     55000.0
3      Sales     70000.0     60000.0

--- Departments with Average Salary > 70k ---

  department  average_salary
0         IT         83750.0

In [ ]:
case_query = """
SELECT
    name,
    salary,
    CASE
        WHEN salary >= 80000 THEN 'High Salary'
        WHEN salary >= 60000 THEN 'Medium Salary'
        ELSE 'Low Salary'
    END AS salary_category
FROM Employees
ORDER BY salary DESC;
"""
fetch_and_display(case_query, "Employees with Salary Categories using CASE")

--- Employees with Salary Categories using CASE ---

             name   salary salary_category
0     Ella Garcia  92000.0     High Salary
1        Amy Wang  90000.0     High Salary
2        Wendy Wu  88000.0     High Salary
3      Sam Taylor  85000.0     High Salary
4    Olivia Lewis  82000.0     High Salary
5       Grace Lee  80000.0     High Salary
6     Karen Green  78000.0   Medium Salary
7       Ben Davis  76000.0   Medium Salary
8   Charlie Brown  75000.0   Medium Salary
9      Xavier Lee  74000.0   Medium Salary
10     Tina Adams  72000.0   Medium Salary
11    Peter Scott  70000.0   Medium Salary
12      Cathy Kim  70000.0   Medium Salary
13     Yara Singh  69000.0   Medium Salary
14      Liam Hall  68000.0   Medium Salary
15       Uma Khan  67000.0   Medium Salary
16    Quinn Baker  66000.0   Medium Salary
17     Harry King  65000.0   Medium Salary
18      Mia Young  64000.0   Medium Salary
19      Eve Adams  63000.0   Medium Salary
20     David Chen  63000.0   Medium Salary
21   Diana Prince  62000.0   Medium Salary
22     Zack Patel  62000.0   Medium Salary
23      Ivy Davis  61000.0   Medium Salary
24    Victor Chen  61000.0   Medium Salary
25    Alice Smith  60000.0   Medium Salary
26    Rachel Hill  60000.0   Medium Salary
27     Noah Clark  59000.0      Low Salary
28    Frank White  58000.0      Low Salary
29    Jack Miller  57000.0      Low Salary
30    Bob Johnson  55000.0      Low Salary

In [ ]:

subquery_example = """
SELECT name, salary
FROM Employees
WHERE salary > (SELECT AVG(salary) FROM Employees);
"""
fetch_and_display(subquery_example, "Employees Earning More Than Average Salary (Subquery)")


create_view_sql = """
CREATE VIEW ActiveEmployees AS
SELECT id, name, department, salary, hire_date
FROM Employees
WHERE is_active = 1;
"""
cursor.execute(create_view_sql)
conn.commit()
print("View 'ActiveEmployees' created successfully.")


fetch_and_display("SELECT * FROM ActiveEmployees;", "Querying the ActiveEmployees View")

--- Employees Earning More Than Average Salary (Subquery) ---

             name   salary
0   Charlie Brown  75000.0
1       Grace Lee  80000.0
2     Karen Green  78000.0
3    Olivia Lewis  82000.0
4     Peter Scott  70000.0
5      Sam Taylor  85000.0
6      Tina Adams  72000.0
7        Wendy Wu  88000.0
8      Xavier Lee  74000.0
9        Amy Wang  90000.0
10      Ben Davis  76000.0
11      Cathy Kim  70000.0
12    Ella Garcia  92000.0

View 'ActiveEmployees' created successfully.

--- Querying the ActiveEmployees View ---

    id           name department   salary   hire_date
0    1    Alice Smith      Sales  60000.0  2020-01-15
1    2    Bob Johnson  Marketing  55000.0  2019-03-22
2    3  Charlie Brown         IT  75000.0  2021-07-01
3    4   Diana Prince         HR  62000.0  2018-11-11
4    5      Eve Adams      Sales  63000.0  2020-02-20
5    7      Grace Lee         IT  80000.0  2022-01-01
6    8     Harry King         HR  65000.0  2017-09-01
7    9      Ivy Davis      Sales  61000.0  2020-04-01
8   10    Jack Miller  Marketing  57000.0  2019-06-15
9   11    Karen Green         IT  78000.0  2021-09-01
10  12      Liam Hall         HR  68000.0  2018-03-01
11  13      Mia Young      Sales  64000.0  2020-05-05
12  14     Noah Clark  Marketing  59000.0  2019-07-20
13  16    Peter Scott         HR  70000.0  2017-10-10
14  17    Quinn Baker      Sales  66000.0  2020-06-10
15  18    Rachel Hill  Marketing  60000.0  2019-08-01
16  19     Sam Taylor         IT  85000.0  2022-05-01
17  20     Tina Adams         HR  72000.0  2018-05-01
18  21       Uma Khan      Sales  67000.0  2020-07-15
19  22    Victor Chen  Marketing  61000.0  2019-09-01
20  23       Wendy Wu         IT  88000.0  2022-07-01
21  24     Xavier Lee         HR  74000.0  2018-07-01
22  25     Yara Singh      Sales  69000.0  2020-08-20
23  27       Amy Wang         IT  90000.0  2022-09-01
24  28      Ben Davis         HR  76000.0  2018-09-01
25  29      Cathy Kim      Sales  70000.0  2020-09-10
26  30     David Chen  Marketing  63000.0  2019-11-01
27  31    Ella Garcia         IT  92000.0  2022-11-01

In [ ]:
create_index_sql = "CREATE INDEX idx_department ON Employees (department);"
cursor.execute(create_index_sql)
conn.commit()
print("Index 'idx_department' created on 'Employees' table.")

alter_table_add_col_sql = "ALTER TABLE Employees ADD COLUMN email TEXT;"
cursor.execute(alter_table_add_col_sql)
conn.commit()
print("Column 'email' added to 'Employees' table.")

update_email_sql = "UPDATE Employees SET email = LOWER(REPLACE(name, ' ', '.')) || '@example.com' WHERE id IN (1, 2, 3);"
cursor.execute(update_email_sql)
conn.commit()
print("Emails updated for some employees.")

fetch_and_display("SELECT id, name, email FROM Employees WHERE id IN (1, 2, 3);", "Employees with updated email")

Index 'idx_department' created on 'Employees' table.
Column 'email' added to 'Employees' table.
Emails updated for some employees.

--- Employees with updated email ---

   id           name                      email
0   1    Alice Smith    alice.smith@example.com
1   2    Bob Johnson    bob.johnson@example.com
2   3  Charlie Brown  charlie.brown@example.com

In [ ]:
update_sql = "UPDATE Employees SET salary = salary * 1.10 WHERE department = 'IT';"
cursor.execute(update_sql)
conn.commit()
print("Salaries updated for IT department employees.")

fetch_and_display("SELECT name, department, salary FROM Employees WHERE department = 'IT';", "IT Employees after Salary Update")

delete_sql = "DELETE FROM Employees WHERE is_active = 0;"
cursor.execute(delete_sql)
conn.commit()
print("Inactive employees deleted.")

fetch_and_display("SELECT name, is_active FROM Employees WHERE is_active = 0;", "Remaining Inactive Employees (should be empty)")
fetch_and_display("SELECT COUNT(*) FROM Employees;", "Total Employees After Deletion")

Salaries updated for IT department employees.

--- IT Employees after Salary Update ---

            name department    salary
0  Charlie Brown         IT   82500.0
1      Grace Lee         IT   88000.0
2    Karen Green         IT   85800.0
3   Olivia Lewis         IT   90200.0
4     Sam Taylor         IT   93500.0
5       Wendy Wu         IT   96800.0
6       Amy Wang         IT   99000.0
7    Ella Garcia         IT  101200.0

Inactive employees deleted.

--- Remaining Inactive Employees (should be empty) ---

Empty DataFrame
Columns: [name, is_active]
Index: []

--- Total Employees After Deletion ---

   COUNT(*)
0        28

In [ ]:
drop_table_sql = "DROP TABLE IF EXISTS Employees;"
cursor.execute(drop_table_sql)
conn.commit()
print("Table 'Employees' dropped successfully.")


drop_view_sql = "DROP VIEW IF EXISTS ActiveEmployees;"
cursor.execute(drop_view_sql)
conn.commit()
print("View 'ActiveEmployees' dropped successfully.")

conn.close()
print("Database connection closed.")

Table 'Employees' dropped successfully.
View 'ActiveEmployees' dropped successfully.
Database connection closed.

i need a code for SQL to do it in the google colab that must cover the all SQL basics functions like creating table,joining table,updation and deletions. make it more professional with all basics topics covered.